### ISSUE TITLE
Attempted to add FORMOSAT-5 via NORAD ID, did not populate satellite

### ISSUE THREAD

**Issue by messerjon** [CSCI401TEAM/Poseidon#25]
I selected by S-Band list, selected By Catalog # and then attempted to add 42920. No response. Then I searched for Formosat and it returned 5 results. Screenshot below to show the response for the By Name response. 

<img width="298" alt="Screenshot 2024-04-09 at 3 07 04 PM" src="https://github.com/CSCI401TEAM/Poseidon/assets/157428469/789aea8c-4018-4f87-8409-8dbc6f3e12e1">

The TLE it should have found is: 
1 42920U 17049A   24100.57692010  .00000281  00000-0  82472-4 0  9993
2 42920  98.2924 179.2855 0011074  26.8239 333.3526 14.50888519350870

**Comment by sidqian123** [comment]
mark as resovled
