### ISSUE TITLE
Is there a way to determine that it has the latest catalogs or is it pulling them each on query?

### ISSUE THREAD

**Issue by messerjon** [CSCI401TEAM/Poseidon#26]
I believe this is a black box problem, I have no means of determining if the tool is finding the most recent TLE.

**Comment by sidqian123** [comment]
resolved

**Comment by messerjon** [comment]
I like the implemented fix

**Comment by sidqian123** [comment]
thx! is there an issue with it?

**Comment by messerjon** [comment]
No, I was trying to say I liked the fixOn Apr 23, 2024, at 7:24 AM, Sid Qian ***@***.***> wrote:﻿
thx! is there an issue with it?

**Comment by sidqian123** [comment]
Oh no I saw you reopened this issue so I wonder if anything went wrong!

**Comment by messerjon** [comment]
Nope, I am just clueless still with GitHubOn Apr 23, 2024, at 7:50 AM, Sid Qian ***@***.***> wrote:﻿
Oh no I saw you reopened this issue so I wonder if anything went wrong!
