### ISSUE TITLE
Searched for 27424 and it found no return. Searched for Aqua and it found AQUA (27424)

### ISSUE THREAD

**Issue by messerjon** [CSCI401TEAM/Poseidon#27]
This is a strange one. It found AQUA and associated it to the correct TLE, but it did not found it by the correct NORAD ID. 

<img width="305" alt="Screenshot 2024-04-09 at 3 11 40 PM" src="https://github.com/CSCI401TEAM/Poseidon/assets/157428469/516f766f-2d3f-4d18-887f-a0d274de89d4">

**Comment by sidqian123** [comment]
mark as resovled
