### ISSUE TITLE
When I click "By Name" the button says "Search", but when I click "By Catalog #" it says says "Add"

### ISSUE THREAD

**Issue by messerjon** [CSCI401TEAM/Poseidon#31]
<img width="300" alt="Screenshot 2024-04-09 at 3 25 19 PM" src="https://github.com/CSCI401TEAM/Poseidon/assets/157428469/68578405-0faa-4c40-828a-a1469028b84f">

<img width="301" alt="Screenshot 2024-04-09 at 3 25 11 PM" src="https://github.com/CSCI401TEAM/Poseidon/assets/157428469/dde89428-ea48-4af7-b81a-66e01999df9c">

**Comment by clasli** [comment]
Hey Jonathan, this was intentional because currently, when you enter a catalog number, it doesn't display a list of search results but instead directly adds that satellite to the list. Would you prefer a different implementation?
